import {
  Body,
  Controller,
  Get,
  HttpException,
  HttpStatus,
  Logger,
  Post,
  Res,
  UseGuards,
  ValidationPipe,
} from '@nestjs/common';
import { PdfGeneratorService } from './pdf-generator.service';
import { Request, Response } from 'express'; // Importing from express
import { CreatePdfDTO } from './pdf.dto';
import { ApiTags } from '@nestjs/swagger';

import { Injectable } from '@nestjs/common';
import { Roles, UserGuard } from '@company/user-lib';

@Injectable()
@ApiTags('PDF Generator')
@UseGuards(UserGuard)
@Controller('pdf/generator')
export class PdfGeneratorController {
  private readonly logger = new Logger(PdfGeneratorController.name);

  constructor(private pdfGeneratorService: PdfGeneratorService) {}

  // POST: http://localhost:3005/api/v1/pdf/generator
  @Post()
  @Roles(['CreatePDF', 'pdf-generator-service'])
  async createPDF(
    @Body() createPdf: CreatePdfDTO,
    @Res() res: Response
    // @Req() req: Request
  ) {
    this.logger.log('incoming POST to api/v1/pdf/generator');
    // console.log(req.headers);

    const response = await this.pdfGeneratorService.createPDF(createPdf);

    // failed to create the pdf ?
    if (response === null)
      throw new HttpException(
        'PDF creation failed ',
        HttpStatus.INTERNAL_SERVER_ERROR
      );

    // set headers for Download when everything worked fine
    res.setHeader('Content-Type', 'application/pdf');
    res.setHeader('Content-Disposition', 'attachment; filename=generated.pdf;');

    res.end(response);
  }

  // DEBUG:
  // http://kubernetes.docker.internal/api/v1/pdf/generator/test
  // @Get('test')
  // async test() {
  //   return 'ok';
  // }

  // DEV:
  // Route to catch the autogenerated PDF while developing
  // GET: http://localhost:3005/api/v1/pdf/generator/debug
  // @XRoles(['CreatePDF'])
  // @Header('Content-Type', 'application/pdf')
  // @Header('Content-Disposition', 'attachment; filename=generated.pdf;')
  @Get('debug')
  async getData(@Res() res: Response) {
    // allways disable this route in production!
    if (process.env['NODE_ENV'] === 'production')
      throw new HttpException('not found', HttpStatus.NOT_FOUND);
    // create the debug PDF from the sources in the tools folder
    // see: projects/pdf-generator/tools/pdf-environment/html
    const response = await this.pdfGeneratorService.debug();

    if (response === null)
      throw new HttpException(
        'PDF creation failed ',
        HttpStatus.INTERNAL_SERVER_ERROR
      );

    // set headers for Download when everything worked fine
    res.setHeader('Content-Type', 'application/pdf');
    res.end(response);
  }
}
